const MODULES=[['dashboard','Dashboard'],['leads','Leads'],['companies','Companies'],['contacts','Contacts'],['deals','Deals'],['activities','Activities'],['tasks','Tasks'],['products','Products'],['templates','Templates'],['notes','Notes'],['users','Users'],['websites','Websites'],['settings','Config']];
const SHEETS={
 leads:{sheet:'Leads',title:'Leads',key:'Lead_ID',fields:['Date_Received','Source_ID','Website_ID','Company_Name','Contact_Name','Email','Phone','City','State','Country','Industry','Requirement','Quantity','Estimated_Value','Currency','Status','Stage_ID','Assigned_To','Priority','Tags','Message','Reference_Image_Link','Catalogue_Sent','Next_Followup_Date','Created_Date','Updated_Date']},
 companies:{sheet:'Companies',title:'Companies',key:'Company_ID',fields:['Company_Name','Industry','Company_Website','GST_No','Address','City','State','Country','Phone','Email','Account_Owner','Source_ID','Website_ID','Client_Type','Created_Date']},
 contacts:{sheet:'Contacts',title:'Contacts',key:'Contact_ID',fields:['Company_ID','Full_Name','Designation','Email','Phone','Alt_Phone','Is_Primary','Created_Date']},
 deals:{sheet:'Deals',title:'Deals',key:'Deal_ID',fields:['Deal_Name','Lead_ID','Company_ID','Contact_ID','Stage_ID','Value','Currency','Probability_%','Expected_Close_Date','Actual_Close_Date','Owner','Status','Lost_Reason','Created_Date']},
 activities:{sheet:'Activities',title:'Activities',key:'Activity_ID',fields:['Related_To_Type','Related_To_ID','Activity_Type','Subject','Notes','Activity_Date','Activity_Time','Duration_Min','Outcome','Next_Action','Next_Followup_Date','Assigned_To','Status']},
 tasks:{sheet:'Tasks',title:'Tasks',key:'Task_ID',fields:['Title','Description','Related_To_Type','Related_To_ID','Due_Date','Priority','Status','Assigned_To','Created_By','Created_Date']},
 products:{sheet:'Products',title:'Products',key:'Product_ID',fields:['Product_Name','Category','Website_ID','Fabric_Spec','HSN_Code','Unit','Unit_Price','Currency','Certification','Description','Stock_Status','Image_URL']},
 templates:{sheet:'Templates',title:'Templates',key:'Template_ID',fields:['Template_Name','Channel','Website_ID','Subject','Body','Category','Created_By']},
 notes:{sheet:'Notes',title:'Notes',key:'Note_ID',fields:['Related_To_Type','Related_To_ID','Note_Text','Created_By','Created_Date']},
 users:{sheet:'Users',title:'Users',key:'User_ID',fields:['Full_Name','Email','Password_Hash','Phone','Role','Department','Status','Date_Joined','Last_Login']},
 websites:{sheet:'Websites',title:'Websites',key:'Website_ID',fields:['Website_Name','URL','Hosting_Platform','Focus_Category','Is_Active']},
 settings:{sheet:'Config',title:'Config',key:null,fields:['Config_Type','Value','Extra_Info','Is_Active']}
};
let DATA={},CURRENT='dashboard';
function $(id){return document.getElementById(id)} function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))} function toast(m){$('toast').textContent=m;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),2500)} function toggleMenu(){$('sidebar').classList.toggle('open')}
function showLogin(){$('loginView').classList.remove('hidden');$('appView').classList.add('hidden')} function showApp(){$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');$('userInfo').textContent=(USER.name||USER.email)+' • '+(USER.role||'');renderNav();renderPage()}
function logout(){clearSession();DATA={};showLogin()}
$('loginForm').addEventListener('submit',e=>{e.preventDefault();$('loginError').textContent='Signing in...';api('login',{email:$('loginEmail').value,password:$('loginPassword').value},r=>{if(!r?.success){$('loginError').textContent=r?.error||'Login failed';return}setSession(r.user,r.token);showApp();loadData()},e=>$('loginError').textContent=e.error||'Network error')});
function loadData(){api('getAllData',{},r=>{if(!r?.success){toast(r?.error||'Data load failed');return}DATA=r.data||{};renderPage()},e=>toast(e.error||'Data load failed'))}
function renderNav(){$('nav').innerHTML=MODULES.map(x=>`<button class="${CURRENT===x[0]?'active':''}" onclick="go('${x[0]}')">${x[1]}</button>`).join('')}
function go(v){CURRENT=v;$('sidebar').classList.remove('open');renderNav();renderPage()}
function rowsFor(k){return DATA[SHEETS[k]?.sheet]||[]}
function renderPage(){if(CURRENT==='dashboard')return dashboard();tablePage(CURRENT)}
function dashboard(){const leads=rowsFor('leads'),deals=rowsFor('deals'),tasks=rowsFor('tasks'),companies=rowsFor('companies');const openDeals=deals.filter(x=>String(x.Status).toLowerCase()==='open');const pipeline=openDeals.reduce((a,x)=>a+Number(x.Value||0),0);const due=tasks.filter(x=>String(x.Status).toLowerCase()!=='completed').length;$('content').innerHTML=`<div class="page-title"><div><h1>Dashboard</h1><div class="sub">Chaitanya Impex CRM</div></div><div class="actions"><button class="btn btn-secondary" onclick="loadData()">Refresh</button></div></div><div class="stats"><div class="stat"><div class="l">Total Leads</div><div class="n">${leads.length}</div></div><div class="stat"><div class="l">Companies</div><div class="n">${companies.length}</div></div><div class="stat"><div class="l">Open Deals</div><div class="n">${openDeals.length}</div></div><div class="stat"><div class="l">Open Tasks</div><div class="n">${due}</div></div></div><div class="card"><div class="card-head"><div class="card-title">Open Pipeline</div><strong>₹ ${pipeline.toLocaleString('en-IN')}</strong></div><div class="empty">Use Leads, Deals, Activities and Tasks to manage the sales process.</div></div>`}
function tablePage(k){const cfg=SHEETS[k];if(!cfg){dashboard();return}const rows=rowsFor(k),cols=cfg.fields.slice(0,8);$('content').innerHTML=`<div class="page-title"><div><h1>${cfg.title}</h1><div class="sub">${rows.length} records</div></div><div class="actions"><button class="btn btn-primary" onclick="openForm('${k}')">+ Add</button><button class="btn btn-secondary" onclick="loadData()">Refresh</button></div></div><div class="card"><div class="table-wrap">${rows.length?`<table><thead><tr><th>Actions</th>${cols.map(c=>`<th>${c.replaceAll('_',' ')}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr><td><button class="btn btn-secondary" onclick='openForm("${k}",${JSON.stringify(r).replaceAll("'","&#39;")})'>Edit</button></td>${cols.map(c=>`<td>${esc(r[c])}</td>`).join('')}</tr>`).join('')}</tbody></table>`:`<div class="empty">No records found.</div>`}</div></div>`}
function openForm(k,row=null){const cfg=SHEETS[k];$('modalTitle').textContent=(row?'Edit ':'Add ')+cfg.title;$('modalBody').innerHTML=`<div class="grid2">${cfg.fields.map(f=>{const val=row?row[f]??'':'';const type=/date/i.test(f)?'date':/value|qty|quantity|probability|duration|price/i.test(f)?'number':'text';return `<div class="field"><label>${f.replaceAll('_',' ')}</label>${['Body','Description','Notes','Note_Text','Message','Requirement'].includes(f)?`<textarea id="f_${f}" rows="4">${esc(val)}</textarea>`:`<input id="f_${f}" type="${type}" value="${esc(val)}">`}</div>`}).join('')}</div>`;$('modalSave').onclick=()=>saveForm(k,row);$('modal').classList.remove('hidden')}
function closeModal(){$('modal').classList.add('hidden')}
function saveForm(k,row){const cfg=SHEETS[k],data={};cfg.fields.forEach(f=>{data[f]=$('f_'+f)?.value??''});if(row&&cfg.key)data[cfg.key]=row[cfg.key];api(row?'updateRecord':'createRecord',{sheet:cfg.sheet,key:cfg.key,keyValue:row&&cfg.key?row[cfg.key]:'',data},r=>{if(!r?.success){toast(r?.error||'Save failed');return}closeModal();toast('Saved');loadData()},e=>toast(e.error||'Save failed'))}
if(USER&&TOKEN){showApp();loadData()}else showLogin();
